In [ ]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [ ]:
df.shape

(569, 33)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [ ]:
# drop irrelevant cols
df.drop(columns=['id', 'Unnamed: 32'], inplace=True)

In [ ]:
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

> On balance, fewer times > more times. Like, if a * (b + c) == (a * b) + (a * c), you might as well go with a * (b + c) because the scalar a is only applied once (in other words, the associated computation graph will have fewer nodes). As a general rule, fewer computational steps translates into greater computational efficiency, as you acknowledged.



> That said, if your transformation involves statistics computed from the entire distribution, like centering or standardizing, then you should apply them after the split. This is because if you compute e.g., the mean of the entire dataset, then rescale everything using that one mean, then split into train and test, this means that information from your test set will have leaked into your train set via that overall mean, and vice versa. So your model will be able in some sense to cheat during testing/cross-validation.

- reddit

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(df.drop(columns=['diagnosis']), df['diagnosis'], test_size=0.2, random_state=42)

In [ ]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [ ]:
x_train.shape

(455, 30)

In [ ]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

In [ ]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [ ]:
y_test

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1])

In [ ]:
print(encoder.classes_) # 0 for B, 1 for M

['B' 'M']


In [ ]:
y_test

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1])

In [ ]:
# convert np arrays to tensors
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [ ]:
x_train_tensor.shape

torch.Size([455, 30])

In [ ]:
y_train_tensor.shape

torch.Size([455])

In [ ]:
# model definition (single neuron)

class NeuralNet():
  def __init__(self, X) -> None:
    # initialise random weights
    self.weights = torch.rand(X.shape[1], 1, requires_grad=True, dtype=float)
    # initialise zero bias
    self.bias = torch.zeros(1, requires_grad=True, dtype=float)

  def forward(self, X):
    z = torch.matmul(X, self.weights) + self.bias
    return torch.sigmoid(z)

  def get_loss(self, y, y_pred): #binary cross entropy since binary classification prob
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7 # very small no.
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon) # makes sure ypred values stay between epsilon and 1-epsilon, otherwise issue with log for values 0 and 1

    loss = -(y * torch.log(y_pred) + (1 - y) * torch.log(1 - y_pred)).mean()
    return loss

In [ ]:
# set parameters
lr = 0.1
epochs = 20

In [ ]:
model = NeuralNet(x_train_tensor)

for epoch in range(epochs):
  y_pred = model.forward(x_train_tensor)

  loss = model.get_loss(y_train_tensor, y_pred)

  loss.backward() # backward pass on computation graph from loss root node

  with torch.no_grad():
    model.weights -= lr*model.weights.grad # Wnew = Wold - lr*dL/dW
    model.bias -= lr*model.bias.grad

  # zero gradients to prevent gradient overflow
  model.weights.grad.zero_() # '_' for inplace
  model.bias.grad.zero_()

  print(f'Epoch: {epoch+1}, Loss = {loss}')

Epoch: 1, Loss = 3.080351367846416
Epoch: 2, Loss = 2.933061727109148
Epoch: 3, Loss = 2.7852956768469563
Epoch: 4, Loss = 2.6324106069369826
Epoch: 5, Loss = 2.4727300703391273
Epoch: 6, Loss = 2.305893450652803
Epoch: 7, Loss = 2.1437897546316
Epoch: 8, Loss = 1.9826157171359742
Epoch: 9, Loss = 1.8223907353584936
Epoch: 10, Loss = 1.6685653060635208
Epoch: 11, Loss = 1.5228781567253453
Epoch: 12, Loss = 1.3897323219207223
Epoch: 13, Loss = 1.2698369575350794
Epoch: 14, Loss = 1.1627218646226192
Epoch: 15, Loss = 1.0727267714559525
Epoch: 16, Loss = 0.9999724803616047
Epoch: 17, Loss = 0.9434924648581758
Epoch: 18, Loss = 0.9012212094099594
Epoch: 19, Loss = 0.8703371552130353
Epoch: 20, Loss = 0.8478643041805495


In [ ]:
model.weights.shape

torch.Size([30, 1])

In [ ]:
model.bias

tensor([-0.1288], dtype=torch.float64, requires_grad=True)

In [ ]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.5).float() # 0 if <5, else 1
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5150815844535828
